### ISSUE TITLE
Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by rharting** [Sustainsys/Saml2#1004]
Our identity provider made some changes to depreciate SSL cipher suites over the weekend and now our .net apps that are using sustainsys.saml2 (0.23) no longer work.  I was using kentor 0.21, so I upgraded to 0.23 hoping that would help using nuget upgrade (and then followed directions to change names in web.config, as well as set modulePath = "/AuthServices" to make compatible. There was no change in behavior. I am using .net framework 4.6.2.  Can anyone offer me any other clues? Any help at all would be greatly appreciated. 
Here is the error message I receive:
`[IOException: Authentication failed because the remote party has closed the transport stream.]
   System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) +8342382
   System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) +186
   System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) +345
   System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) +203
   System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) +769
   System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) +355
   System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) +20
   System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) +82
   System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) +1105
   System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) +60
   System.Net.ConnectStream.WriteHeaders(Boolean async) +463

[WebException: The underlying connection was closed: An unexpected error occurred on a send.]
   System.Net.WebClient.OpenRead(Uri address) +521
   Sustainsys.Saml2.Metadata.MetadataLoader.Load(String metadataLocation, IEnumerable`1 signingKeys, Boolean validateCertificate, String minIncomingSigningAlgorithm) +108
   Sustainsys.Saml2.Metadata.MetadataLoader.LoadIdp(String metadataLocation, Boolean unpackEntitiesDescriptor) +31
   Sustainsys.Saml2.IdentityProvider.DoLoadMetadata() +411
   Sustainsys.Saml2.IdentityProvider.ReloadMetadataIfRequired() +162
   Sustainsys.Saml2.IdentityProvider.CreateAuthenticateRequest(Saml2Urls saml2Urls) +73
   Sustainsys.Saml2.WebSso.SignInCommand.InitiateLoginToIdp(IOptions options, IDictionary`2 relayData, Saml2Urls urls, IdentityProvider idp, Uri returnUrl) +46
   Sustainsys.Saml2.WebSso.SignInCommand.Run(EntityId idpEntityId, String returnPath, HttpRequestData request, IOptions options, IDictionary`2 relayData) +659
   Sustainsys.Saml2.WebSso.SignInCommand.Run(HttpRequestData request, IOptions options) +181
   Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e) +365
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +139
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +88`

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.

**Comment by Ravivishnubhotla** [comment]
@rharting @AndersAbel Hey Guys i know this was support question. But did you guys find a resolution to this issue. I am currently having the same issue in our environment especially hosting this with IdentityServer4 with SAML with Org Idp, It is hosted in Load balancer environment. Any idea what the issue was and if there was any resolution?

**Comment by rharting** [comment]
In my case, Ravivishnubhotla, my .NET code needed to specify the use of TLS 1.2
