### ISSUE TITLE
Can I configure ReturnUrl on logout?

### ISSUE THREAD

**Issue by Dratskapoo** [Sustainsys/Saml2#1006]
Hi,

I have set up SLO for a MVC-project and it seems to work but the problem is that we get returned to the entrypoint after logout. In my dev-environment I am using the stubidp and i will get that startscreen for stubidp directly after logout and that is ok but in a testenvironment with ADFS as idp it will automatically log in again. I have tested to logout by adding /AuthServices/Logout?ReturnUrl=/status (status-page does not require login) and it seems to work since i will land on the statuspage. If i instead would set http://www.google.se as ReturnUrl it does not work. So my question is if it is possible to configure what is sent in to ReturnUrl for logout in WebConfig and does it always have to be relative to my applications url?

Kind Regards
Eric

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
