### ISSUE TITLE
Signature Verify failing due to missing encoded characters

### ISSUE THREAD

**Issue by manfredfunco** [Sustainsys/Saml2#1009]
Our IDP returns mailing address in the a <saml:AttributeValue>. Some address have carriage returns in them (in addition to line feed). The signature validation fails for these users because the XML response on the IDP was signed with a &#xD; (encoded carriage return). After this there is also a line feed that you may not be able to see in the snippet below. When I decode the base64 response manually and check the signature, the XML validates successfully. 

`<saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:anyType">123 Maple Ln&#xD;
#300</saml:AttributeValue>
`

However, I can see in the log of the component that when validating the signature, the &#xD; symbol is missing. The line feed is there. Therefore, the signature check because the XML has been altered.

We're using the Owin version in our site. Is there a configuration that can be made to prevent the encoded characters from being removed?

**Comment by AndersAbel** [comment]
Looks like a bug if it decodes things before signature validation. If you can help debugging and see where the decoding is done, that would be really helpful.

**Comment by explunit** [comment]
Would this be a canonicalization issue? If I recall correctly the code is strict on what it accepts (for good reasons).

**Comment by AndersAbel** [comment]
@explunit I don't think so. The code is very strict on what transforms it accepts, but if an invalid/custom transform caused this there should be an exception message logged that indicates that:  "Transform \"" + transform.Algorithm + "\" found in Xml signature SHOULD NOT be used with SAML2.".

I think this might be due to the XML being parsed and possibly re-exported as a string before validation. I don't remember exactly how it's done - it has changed over the years.

**Comment by manfredfunco** [comment]
I see that the HttpRequestData "request" passed into AcsCommand->Run. This request contains the base64 encoded response which contains the encoded carriage return. In this particular test case, it's "&#13;" (as well as an actual line feed). On line 50 of AcsCommand.cs binding.Unbind is called passing in the request. I confirmed that unbindResult.Data.OuterXml does not have the character, just the line feed. Therefore, something is happening in the unbind process. I hope this helps.

**Comment by manfredfunco** [comment]
I narrowed this down further. In Saml2PostBinding.cs line 38, there's a call to XmlHelpers.XmlDocumentFromString to create the XmlDocument from the base64 encoded string. In XmlHelpers.cs, line 46 is the call to XmlDocument.LoadXml. 

I confirmed that the resulting XmlDocument is missing the encoded carriage return contained in the base64 string. I don't see any options to set here that could resolve the issue but will keep looking.

**Comment by AndersAbel** [comment]
@manfredfunco Thanks for your efforts narrowing this down. Is this a bug in the .NET XmlDocument? In that case we are kind of stuck since SignedXml requires the data to be parsed into an XmlDocument to do the signature validation. An alternative would be to look at the enveloped signature reader that is part of the new Microsoft.IdentityModel Nuget packages. It's a separate set of code to validate XML signatures. We would have to look very carefully at it though, to make sure it is secure in the context of the SAML2P complexity of signatures where both responses and the contained assertions can be signed.

**Comment by manfredfunco** [comment]
Hey @AndersAbel. I agree with your assessment and am thinking this may not be a "defect". In this case there is data in attribute values collected from HTML forms that may have inconsistent new line/carriage return characters. Because systems treat these characters differently, it seems difficult to implement a solution that handles all cases. The fact that XmlDocument is treating &#xD; as an actual carriage return character isn't necessary a defect. There may be cases (maybe most cases?) where this is what it's supposed to do.

Our client did ask why is this not a problem with the other sites that are receiving the same SSO response. It's difficult to answer but possibly the developers at the time did run into this and are doing something else custom to handle this, or turning off signature verification off complete (eek). 

I believe the ideal solution is for the other site that collects this data to cleanse the data before saving so that the XML sent in the SAML response is consistent. For example, simply removing carriage return characters (and keeping the line feed) may all that's needed in this particular case.

I'm considering this not a bug and closed from my standpoint. We're working around this by simply omitting the offending field in the SAML response. I may address this at some point in the future though and will enter another issue if I see something that can be changed in the component. 

Thanks for the help!

**Comment by AndersAbel** [comment]
Ok, marking this as won't fix for now (a closed bug without won't-fix marking will turn up in my filter of fixed issues for a release)
