### ISSUE TITLE
Support .Net Framework 4.6.2 in Sustainsys.Saml2 Version 2.0

### ISSUE THREAD

**Issue by techgeek03** [Sustainsys/Saml2#1024]
Hello,
We have been using the package for some time and support all the good job and effort put :) 

We are targeting .Net Framework 4.6.2 and would like to use the new package version 2.0. However, the new version requires  .Net Framework 4.7.
Since the package already supports netStandard 2 and .Net Framework is backward compatible there is no reason why not to support 4.6.2. Can you please include this target framework in the Nuget package?

**Comment by AndersAbel** [comment]
The reason is the ECDSA signature support, which was only added in .NET Framework 4.7. I first tried to use only a single netstandard2.0 target, but then ran into issues with System.Configuration that required the consuming application to apply a lot of workarounds. I want the library to be easy to consume, so I added the net47 target to remove the need for workarounds.

Is there any special reason why you want to target 4.6.2 not and not bump to 4.7?

**Comment by techgeek03** [comment]
I see. I was about to suggest to target only netstandard2.0 but if that complicates the configuration then it makes sense to target 4.7 as well. We are not ready with the support for 4.7 on all our servers. I guess we will wait with upgrading to the package version 2.0

**Comment by AndersAbel** [comment]
2.0 is essentially the same features as 1.0, but with support for netstandard/netcore. So for now, there is no hurry to upgrade. There is a 2.1 on the way that will contain some new features. But if you have a working solution on 1.0, then you obviously won't need those new features.
