### ISSUE TITLE
Using AcsCommandResultCreated Notification

### ISSUE THREAD

**Issue by j-hurst** [Sustainsys/Saml2#1037]
I am using the latest AspNetCore2 package, and once the AcsCommand has processed the response, I need to redirect it to another URL in my same IdP domain to save off the claims and add additional claims to the claims principal from the database.  

However, when I set the CommandResult Location property in the AcsCommandResultCreated notification, I noticed my cookie did not persist and the claims principal did not persist.

Then in trying to set a new StoredRequestState to pass this information on to my other URL  I get an 'Unprotect ticket failed' error from .NET Core's Cookie Authentication Handler.

Below is my AcsCommandResultCreated Notification:
```
options.Notifications.AcsCommandResultCreated = (commandResult, response) =>
{
	commandResult.RequestState = new Sustainsys.Saml2.StoredRequestState((new Sustainsys.Saml2.Metadata.EntityId("https://myIdP/External/SamlCallback"),
		new Uri("https://myIdP/External/SamlCallback", UriKind.Absolute), new Microsoft.IdentityModel.Tokens.Saml2.Saml2Id(), commandResult.RelayData);
	commandResult.Location = new Uri("https://myIdP/External/SamlCallback", UriKind.Absolute);
	commandResult.SetCookieName = IdentityServerConstants.ExternalCookieAuthenticationScheme;
};
```

It seems like I should be able to process this if I was not getting the 'Unprotect ticket failed' error.  Is this supported; am I passing something incorrectly?

**Comment by AndersAbel** [comment]
You're trying to do something very strange. It feels like you are not fully understanding the Saml2 flow.

The error message you get is because you are storing a Sustainsys.Saml2 relay state cookie under the Asp.Net core external cookie name. The external cookie authentication handler will not be able to decode that cookie contents as a session authentication cookie.

I'm closing this issue here as it is more of  a support issue. Please either ask on Stack Overflow, or mail me at anders@sustainsys.com for commercial support options.

**Comment by j-hurst** [comment]
You are correct.  I was misinterpreting what the state cookie was really supposed to do.  Once I realized that I was able to solve my problem without any issues.

Thanks for all your help!
