### ISSUE TITLE
web config returnUrl not being used

### ISSUE THREAD

**Issue by abhishekakumar** [Sustainsys/Saml2#1038]
Return url in sustainsys.saml2 web config section does not seem to work and it always takes the return url from the request.

I tried both relative url and absolute url and neither worked.

```
<sustainsys.saml2 entityId="https://localhost:44303/Saml2"
returnUrl="~/Schedule/CreateRequest">
  <identityProviders> </identityProviders>
</sustainsys.saml2>
```

```
<sustainsys.saml2 entityId="https://localhost:44303/Saml2"
returnUrl="https://localhost:44303/Schedule/CreateRequest">
    <identityProviders></identityProviders>
</sustainsys.saml2>
```

I am not sure if it's a bug or just me doing something wrong.

### Information needed
1. What nuget packages are you using
Sustainsys.Saml2.Mvc 1.0.0
Sustainsys.Saml2 1.0.0

2. What is the expected behaviour
The request should be returned to the returnUrl specified in the web config.

3. What happens instead.
It always redirects to the url requested before authentication.

### Additional info
Please include
* .Net Framework your application is compiled against (e.g. `net472`, `netcoreap2.1`) = 4.5.2
* .Net Framework installed. This might be different than above. You can compile with net452, but have 4.7.2 installed. = 4.5.2
* Version of Asp.Net MVC / Asp.NET Core used. = Asp.Net MVC 5.2.3.0

Thanks

**Comment by AndersAbel** [comment]
If you have a ReturnUrl specified in the query string in the call to SignIn, that will take precedence. The ReturnUrl in the config is only used if there is none in the query string.

**Comment by abhishekakumar** [comment]
No I am not using any ReturnUrl in the query string or setting that variable in any code.

What I meant was if the request is https://localhost:44303/ then it will get redirected to /(Home) after authentication irrespective of what I have as returnUrl in config. But if the request is https://localhost:44303/Schedule/CreateRequest then it will be redirected to this url after authentication.

**Comment by AndersAbel** [comment]
You probably have forms auth enabled in your web.config. It will automatically redirect any unauthenticated calls to e.g. https://localhost:44303/Schedule/CreateRequest to http://localhost:44393/Saml2/Signin?ReturnUrl=https%3A%2F%2Flocalhost%3A44303%2FSchedule%2FCreateRequest.

So you have a ReturnUrl in your call to SignIn.

This is by design and not a bug. If you want any further assistance on how to handle this, that is a support question. Please ask a question on Stack Overflow or mail anders@sustainsys.com for informtion on commercial support options.
