### ISSUE TITLE
Metadata changes on application pool restart

### ISSUE THREAD

**Issue by pduckers** [Sustainsys/Saml2#1137]
Hi, i'm new to Saml2, but have succesfull implemented these library's to connect to a IDP (adfs) with our webapp with owin. 
I've noticed that the metadata on https://www.ourwebapp.com/saml2 changes when the application pool restarts (for instance). This means that the IDP has to re-read this metadata.
Is this correct? Is there a way to prevent this? Am i missing something on the matter?
Regards
P. Duckers

**Comment by mklinke** [comment]
Not sure if I could answer the question, but as a user of the library, IMHO, it might help if you could indicate what part of the metadata is changing, e.g. by posting an anonymized diff...

**Comment by pduckers** [comment]
Hi mklinke, thanks for replying. I've marked the differences in this screen shot:
![Metadata](https://user-images.githubusercontent.com/30258387/71009229-2e554e00-20ea-11ea-8a79-e65fe0176654.JPG)

**Comment by AndersAbel** [comment]
The metadata document is generated on the fly each time it is requested. The actual metadata contents are the same, but as each reload technically is a new document, it gets a new document ID. The signature of the document of course signs the document ID too. So when the document ID changes, the signature changes too.

But the data is the same, so there is no need to re-read metadata just because of this.
