### ISSUE TITLE
Is HttpModule version 2.4.0 going to be available for .NET framework 4.6.1 like it was for version 2.3.0?

### ISSUE THREAD

**Issue by TuukkaHeiskanen** [Sustainsys/Saml2#1154]
Hi, so is HttpModule 2.4.0 going to be available for .NET framework 4.6.1 in near future? I have been implementing SAML2 authentication for project targeted .NET framework 4.6.1. The library has been working great so far, but the SameSite cookie update for Chrome 80 caught my off guard. I found that version 2.4.0 should fix this issue, but surprisingly it was not supported for .NET 4.6.1 anymore. This was a surprise untill I found commit: https://github.com/Sustainsys/Saml2/commit/e1e5f3e5601b541cf08e6ccdb03c618ecf443868 . In documentation it still states that 4.6.1 is supported "_The package adds an ASP.NET Http Authentication Module that handles SAML SignIn and SignOut It works with the claims model of .NET 4.6.1..._".  Seems like the high level Sustainsys.Saml2 library still supports 4.6.1.

**Comment by AndersAbel** [comment]
The documentation is wrong. The HttpModule with SameSite will require at least .NET 4.7.2 because that's the lowest .NET Framework version where the [`HttpCookie.SameSite` attribute](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpcookie.samesite?view=netframework-4.8) is available. Without that property it is impossible to control the `SameSite` setting of the cookie.
