### ISSUE TITLE
SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: '[PII is hidden]'. Did not match: validationParameters.ValidAudience: '[PII is hidden]' or validationParameters.ValidAudiences: '[PII is hidden]'.]

### ISSUE THREAD

**Issue by takolhe** [Sustainsys/Saml2#1162]
I am facing this issue when trying to access acs

**Comment by galaxyAbstractor** [comment]
I had this as well and it was due to me giving the wrong audience url to my idp. Have you made sure that the audience url you gave your idp is the same as the EntityId you setup the SP with? `options.SPOptions.EntityId ` for example. See the picture and table here: https://saml2.sustainsys.com/en/2.0/identity-server-3-okta.html#step-2-configure-an-application-within-okta

**Comment by AndersAbel** [comment]
Enable PII to your logging: `IdentityModelEventSource.ShowPII = true; `

**Comment by frankus1972** [comment]
I am working with Framework 4.7. How could I enable PII? Some key in web.config ? Thank you

**Comment by AndersAbel** [comment]
@frankus1972 Same setting, put it in any part of the code that runs on startup.
