### ISSUE TITLE
"System.Net.WebException: Too many automatic redirections were attempted" when resolving artifact with Sustainsys.Saml2 2.7.0

### ISSUE THREAD

**Issue by TJ82** [Sustainsys/Saml2#1228]
For one of our products we recently took a big leap by upgrading Sustainsys.Saml2 from version 0.23.0 to the latest available, 2.7.0. It looked like a smooth transition at first and we did not run into any notable issues on our testing grounds.

However, this was not the case at our customer. As it turns out, this version of Sustainsys.Saml2 throws the following exception when attempting to resolve an artifact at their IDP:

> System.Net.WebException: Too many automatic redirections were attempted.
>    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    at System.Net.WebClient.UploadString(Uri address, String method, String data)
>    at Sustainsys.Saml2.Saml2P.Saml2SoapBinding.SendSoapRequest(String payload, Uri destination, IEnumerable`1 clientCertificates)
>    at Sustainsys.Saml2.WebSso.Saml2ArtifactBinding.ResolveArtifact(String artifact, StoredRequestState storedRequestState, IOptions options)
>    at Sustainsys.Saml2.WebSso.Saml2ArtifactBinding.Unbind(HttpRequestData request, IOptions options)
>    at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
>    at Sustainsys.Saml2.Owin.Saml2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()

- I have searched for this specific exception on GitHub, but the only thing that came up was an issue with downloading metadata. That does not seem to be related.
- We have verified that the IDP indeed uses a redirect.
- The IDP in question is federated.

My questions now:

- Is this a bug or expected behaviour?
- Is the number of redirects now somehow limited by design and perhaps configurable? I checked the docs by searching for "redirect", but this did not yield any relevant results.

**Comment by berendengelbrecht** [comment]
We had this issue with SAML2 Arifact binding and SustainSys.Saml2 version 2.8.0. Unfortunately, the issue only occurred with a private IDP maintained by the Dutch Justice Department, in a closed environment, making it quite hard to troubleshoot.

My investigation points to two bugs in SustainSys.Saml2 artifact binding. Note that artifact binding in itself does not appear to be very common, other IDPs we support all use HTTP POST binding and not Artifact binding.

**1. To send an artifact resolution SOAP request, SustainSys.Saml2 uses [WebClient.UploadString.](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.uploadstring?view=net-5.0#System_Net_WebClient_UploadString_System_Uri_System_String_).**
The Justice department IDP detects encoding issues in the uploaded SOAP xml data prepared by `UploadString` and redirects to a 403 error page on their server. In our case, that was the immediate cause of the redirect loop. WebClient always seems to use automatic redirects, making it hard to diagnose the issue at the SP side. You only get the "Too many automatic redirections" exception, without any indication of the URL where you're being redirected.

To fix this issue, I created a fork using `System.Net.HttpClient` rather than `System.Net.WebClient`. `HttpClient` can be configured using manual rather than automatic redirects, allowing me to troubleshoot this issue. While doing this, I found that SustainSys appears to have selected `WebClient` because older versions of `HttpClient` lack support for client certificates. SustainSys is designed to be compatible with Microsoft.Net framework 4.6 and above, but HttpClient needs framework 4.7.1 or newer for proper cliënt certificate support. As we are no longer allowed to use framework versions below 4.7.2 for security reasons, I dropped support for older frameworks in our fork, so that I could use `HttpClient` _and_ client certificates. 

**2. After fixing the redirect issue, the IDP successfully processes the artifact resolution request, but SustainSys throws a validation exception**
`Sustainsys.Saml2.Exceptions.Saml2ResponseFailedValidationException: The SAML Response is not signed and contains unsigned Assertions. Response cannot be trusted.`
Stack trace:
```
at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateSignature(IOptions options, IdentityProvider idp) in SAML2P\Saml2Response.cs:line 535
at Sustainsys.Saml2.Saml2P.Saml2Response.Validate(IOptions options, IdentityProvider idp) in SAML2P\Saml2Response.cs:line 504
at Sustainsys.Saml2.Saml2P.Saml2Response.<CreateClaims>d__66.MoveNext() in SAML2P\Saml2Response.cs:line 595
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options, IDictionary`2 relayData) in SAML2P\Saml2Response.cs:line 586
at Sustainsys.Saml2.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState, IdentityProvider identityProvider, String relayState) in WebSSO\AcsCommand.cs:line 149
at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) in WebSSO\AcsCommand.cs:line 94
```
As far as I can tell, the exception is **incorrect**. The IDP response _is_ signed, but not at the level where SustainSys.Saml2 attempts to validate it. To fix the issue, I implemented the following changes:
- Added validation of the response inside `Saml2ArtifactBinding.ResolveArtifact`:
``` csharp
      var response = Saml2SoapBinding.SendSoapRequest(payload, arsUri, clientCertificates,
        options.SPOptions.Logger); // logger is passed as extra parameter to allow logging inside SendSoapRequest
      if (response.IsSignedByAny(idp.SigningKeys, options.SPOptions.ValidateCertificates, 
          options.SPOptions.MinIncomingSigningAlgorithm))
      {
        options.SPOptions.Logger?.WriteVerbose("Artifact resolved and signature validated: \n" + response.OuterXml);
        return new Saml2ArtifactResponse(response).GetMessage();
      }
      else
      {
        options.SPOptions.Logger?.WriteInformation("ERROR: Signature validation failed for: \n" + response.OuterXml);
        throw new Saml2ResponseFailedValidationException("The SAML Response is not signed. Response cannot be trusted.");
      }
```
- Increased the trust level of the `UnbindResult` returned after `ResolveArtifact` to `TrustLevel.Signature`:
``` csharp
      var data = ResolveArtifact(artifact, request.StoredRequestState, options);
      return new UnbindResult(data, relayState, TrustLevel.Signature); 
        // TrustLevel.Signature can be used because ResolveArtifact validates the signature
```
- added code to bypass signature validation inside the `Saml2Response` class when an `UnbindResult` with `TrustLevel.Signature` was received:
``` csharp
    private void Validate(IOptions options, IdentityProvider idp)
    {
      CheckIfUnsolicitedIsAllowed(options, idp);
      if (_trustLevel != TrustLevel.Signature)
        ValidateSignature(options, idp);
    }
```
Unfortunately, I do not have time to do all the work required to submit my fork as official addition to SustainSys.Saml2. Still I hope that my comments help to resolve the issues with artifact binding in a future version of SustainSys.Saml2. I am very happy that SustainSys.Saml2 is a well-documented and well-supported Open Source product, access to the full source code was essential to troubleshoot the issues in a closed high-security customer environment.

With kind regards,

Berend
