### ISSUE TITLE
QUESTION: Compatibility with .Net Framework in future

### ISSUE THREAD

**Issue by alexander-lysenko-88** [Sustainsys/Saml2#1331]
Hi! I asked this question in my PR, but then decided to raise it as a separate issue as it's a more general one.

As I can see on the wiki the `develop` branch will be used for the `v3` release which will be Asp.Net Core compatible only. Does this mean that .Net Framework version is abandoned from now on? What if I'd like to add a new feature or a bug fix for .Net Framework App?

**Comment by AndersAbel** [comment]
Both `v1` and `v2` support .NET Framework. Both are in maintenance only-mode from an open source perspective. They will receive security updates if needed and will receive critical fixes (like the `SameSite` patch in 1.0.1).

Trying to both develop a new version with reworked architecture and still backport features to `v1` and `v2` turned out to be too much for an open source effort. That is why this decision was made. Instead of working on a new version the time available was spent on the old versions.

For paying customers, the story is different. The work and time spent on these packets is completely funded by the customers that have commercial support packages. That means that for commercial consulting, (almost) everything is doable if we can agree on a price. The conclusion of this is that if you want further features on `v2` (I would really prefer to not touch `v1` any more) you (or rather your organisation) should sign up for a support contract.

**Comment by alexander-lysenko-88** [comment]
Ok, got it, thanks!

and one more clarification :) 
if I (not having a commercial support packages) implement a feature for `v2` on my own and create a pull request with it, will it be accepted or it will depend on volume of changes and affected area?

**Comment by AndersAbel** [comment]
No, I simply don't have the time to put into PR work for non-commercial customers on the `v1` and `v2` branches any more.

**Comment by alexander-lysenko-88** [comment]
Ok, thanks!
