### ISSUE TITLE
Multi tenant configuration in asp.net core

### ISSUE THREAD

**Issue by impathan** [Sustainsys/Saml2#1401]
I have multi tenant application and having multiple azure account for different company and saml configuration. I have hosted angular application on different domain but the backend asp.net core application in single domain. I want to configure multiple saml configuration based on domain which is configured in tenant based on company. 

Can we setup the saml configuration on login request based on the requested domain instead of having the saml configuration in startup class?

**Comment by AndersAbel** [comment]
Yes. Use the `SelectIdentityProvider` notification. If you have a limited number of IdentityProviders, I suggest adding all of them to the IdentityProviders collection and let `SelectIdentityProvider` pick the right one. If you have many of them, you can store them in a DB. Then you also need to override `GetIdentityProvider`

**Comment by impathan** [comment]
Thanks for the reply. Is any sample code available to use the SelectIdentityProvider?

**Comment by AndersAbel** [comment]
No, there is unfortunately not any sample available for that currently.

**Comment by pdonovan** [comment]
How is `SelectIdentityProvider` supposed to select which idP to use? It isn't supplied any context for the request. The SignInCommand.Run() is supplied an HttpRequestData object, but that is passed into the event. What am I missing?

**Comment by joshuafranklinengineeringsystems** [comment]
It’s in the Acs response, you pass the name of the in the Acs callback?Alan TaylorDirector,  Software Engineer+44 7768 831597Joshua Franklin Engineering Systems LimitedRegistered Office: Flat 2 Grove Court, 9 Gumbrell Mews, REDHILL, RH1 1TGVAT Registration Number: 440 7683 87Registered Number: 14299506Registered in England & WalesOn 12 Mar 2025, at 06:51, Paul Donovan ***@***.***> wrote:﻿
  How is SelectIdentityProvider supposed to select which idP to use? It isn't supplied any context for the request. The SignInCommand.Run() is supplied an HttpRequestData object, but that is passed into the event. What am I missing?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



pdonovan left a comment (Sustainsys/Saml2#1401)
How is SelectIdentityProvider supposed to select which idP to use? It isn't supplied any context for the request. The SignInCommand.Run() is supplied an HttpRequestData object, but that is passed into the event. What am I missing?

**Comment by pdonovan** [comment]
What I found worked was to override ASP.NET's `SignInManager.ConfigureExternalAuthenticationProperties()` where you can call the base implementation, then figure out the tenant (e.g. using `this.Context`), then add the name to the AuthenticationProperties.Items dictionary that you return. The values in that dictionary are then available in the dictionary passed to the `SelectIdentityProvider` handler.

**Comment by AndersAbel** [comment]
@pdonovan Yes, that's the right way to handle it. The authentication properties is the way to send parameters to the `SelectIdentityProvider` notification.

To expand a bit about this, I learnt a lesson API design here. The `SelectIdentityProvider` should have had a single parameter which would have been a context of some sort. That way, I could easily have added new properties as needed to the context. Now I didn't go that way and once published, it would be a breaking change to change the signature of the notification.
