### ISSUE TITLE
choose programmaticaly entityId based on page url

### ISSUE THREAD

**Issue by aleha84** [Sustainsys/Saml2#799]
stackoverflow [link](https://stackoverflow.com/questions/46318289/kentor-auth-services-choose-programmaticaly-entityid-based-on-page-url)

I'm integrating our asp.net MVC application with SAML2 Authentication. And using Kentor.AuthServices as module as described at kentor.AuthServices Configuration

Everithing works fine. But next step is to add usage of second service provider (which configured to use another auth mechanisms on server side) only for specified range of pages.

First, how to configure it via web.config to add second SP (not the second IdP in scope of first SP) with different entityId.

And Second, how to switch programmatically to second SP? I assume that it should happend in global.asax file in method Application_BeginRequest, but how?

**Comment by AndersAbel** [comment]
Answered on Stack Overflow:

Using two different SP instances in the same application is a quite rare scenario. But if you are really sure you need it, it can be achieved.

You will have to use the Kentor.AuthServices.Owin package and do the configuration in code - web.config won't do. Register two instances of the middleware. Each one will have their own configuration, including their own SP EntityID. Also make sure to change the ModulePath of at least one of them so that they get different endpoint addresses.

To challenge an authentication from either one, set the right authentication scheme in the challenge (typically in a ChallengeResult returned from a controller)

**Comment by KurtisOliverson** [comment]
I have a similar need, but I just need one SP whose EntityId and ReturnUrl are based on the Uri.Host from the client request.

I believe that Startup.ConfigureAuth() executes too early for this.  Hence, could I configure/reconfigure SPOptions in a notification handler?  If so, is HttpContext.Current.GetOwinContext() the only way to get the URL?  (It's hosted on IIS, in my case.)
