### ISSUE TITLE
SAMLRequest is not correct as unable to decode

### ISSUE THREAD

**Issue by Gillardo** [Sustainsys/Saml2#843]
I am using a SAML2 provider for aspnet core, but had a few problems with them with updating things etc so trying to implement this one instead.

I believe i have set everything up with the following settings (cannot show URLs on public pages)
![image](https://user-images.githubusercontent.com/7406381/32777411-eedbecfe-c92d-11e7-839f-842dd736905e.png)

Now everything loads up etc (edited the sample project), but the URL that it produces on the HTTPRedirect is not correct.  When i copy and paste the request to this page https://idp.ssocircle.com/sso/toolbox/samlDecode.jsp and try to decode it, its says "Failed to decode".  With the other SAML software, it works fine.

Here is an example response that i usually get using my "old" software
![image](https://user-images.githubusercontent.com/7406381/32777544-6fd5fcd2-c92e-11e7-9c7a-a8994d0e8b7a.png)

Also, how can i change the `AssertionConsumerServiceURL` because i would like the response to go to my own controller method after they have logged in, so i can create them a local token and do some other processing.....

**Comment by AndersAbel** [comment]
Can you mail me the URL that is created on the Redirect so that I can check it (anders@sustainsys.com)?

The `AssertionConsumerServiceUrl` isn't configurable and should not be - it's part of the validation of the incoming response. However you can set a redirect url where the Saml2 handler will redirect the browser after a successful validation by the assertion consumer service. Check the sample application in the repo, it does exactly that with a redirect to `ExternalLoginCallback` after the assertion consumer service.

**Comment by Gillardo** [comment]
@AndersAbel sent you an email with details, thanks

**Comment by AndersAbel** [comment]
Debugged, found out it was an Idp issue.
