### ISSUE TITLE
Question - passing extra parameters in authn request

### ISSUE THREAD

**Issue by alexandreabeh** [Sustainsys/Saml2#969]
Is it possible to configure Sustainsys/Kentor to pass along a query parameter in the authn request besides just the SAMLRequest and RelayState? If so, how?

**Comment by AndersAbel** [comment]
The base SingleSignOnService url of the Idp might contain a fixed query string. It's also possible to alter the generated query string in the SignInCommandResultCreated notification.

If you need to pass additional data to the Idp, you might also want to look into adding extension data to the AuthnRequest as extension data. That would require some code changes in the library though.

**Comment by dimuthun** [comment]
I have a similar question. I need to pass 'username' in the query string so that ADFS IDP login page will prepopulate the username. Though I can manipulate the request query string in 'SignInCommandResultCreated' notification event, I don't have the access to application username in this event handler. 
1. Is there any other place whether I can append username query string in this request ?
2. Can't I send the username in the initial redirect url (ie. Saml2/SignIn?idp=xxxxxxxx) ? 
3. Any possibility of relaying the 'username' so that I can access it in SignInCommandResultCreated event ?

**Comment by AndersAbel** [comment]
Issue no longer looks active, closing. Please comment if it should be reopened.

**Comment by dimuthun** [comment]
My question is still open. I need to append username as a query parameter with the generated SAML request. Adding query param is possible in SignInCommandResultCreated event but I am unable to pass username to it since it is an event where I cannot obtain Request properties.

**Comment by taistoonnela** [comment]
Hi Anders, having the same problem. Need to send a customerCode to the internal IdP. What is the recommended way to do it ? 

Plan B is to use Redis and use e.g. RelayState as key. 
But can not find where the RealyState is generated.

Any suggestions?
/taisto

**Comment by AndersAbel** [comment]
RelayState is generated internally and needs to be strongly random for the CSRF protection.

The recommended way to send additional information to the Idp is to use extensions in the AuthnRequest. That is now supported thanks to #598 being implemented. To work with it, override the `AuthenticationRequestCreated` notification and add custom data to the extensions. This is done on an XML level, before the data is serialized and/or compressed and/or signed.
