### ISSUE TITLE
The signature verified correctly with the key contained in the signature, but that key is not trusted

### ISSUE THREAD

**Issue by crataegustess** [Sustainsys/Saml2#974]
Hi folks, I've found instances of this error for our two (new) Okta apps. We cloned these okta app from old apps that still work fine. Signature algorithm on both has been chosen as RSA SHA256
Running: 

- dot net 4.6
- kentor v 0.22.0

We have this in Global.asax:
	

- Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures();

We are loading metadata from file on webserver disk not url endpoint / http address

We tested on web app hosted on IIS8 / 2012R2 and Azure (both show the same error)

I can provide failing request and metadata on request. 
After reading https://github.com/Sustainsys/Saml2/issues/659 and https://github.com/Sustainsys/Saml2/issues/735 I have checked that the certificates appear to match request vs metadata and working metadata vs not working metadata 
Is there anything else I can check?

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. If you want support for free, please open a question on Stack Overflow and tag it with `sustainsys-saml2`.

If you want a guaranteed response, please get in touch at `support@sustainsys.com` to get information about commercial support options.
