### ISSUE TITLE
Cannot use the example project's key from .Net Core in a Core 2.1 project

### ISSUE THREAD

**Issue by rosspace** [Sustainsys/Saml2#976]
I'm using the example core project for configuring my core 2.1 app (I'm using the netstandard branch which I think matches up to the preview nuget package). When I try loading the certificate I get an ArgumentException 'Provided certificate is not valid because it does not contain a private key.' I ran the example project as is and it worked so I'm wondering if this is something that has changed between core 2.0 and 2.1 or is there a problem in the preview nuget package?

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
