### ISSUE TITLE
Cant get Access Token in SAML2 with IdentityServer example

### ISSUE THREAD

**Issue by kishantm** [Sustainsys/Saml2#989]
I have downloaded sample code and running SampleIdentityServer3 project. Configured Okta as a SAML provider.
After login i am getting id_token, but what i expect is, it should issue a token as well through my web api.

Or any other way to send request using this id_token and getting token from my webapi owin for resource access(api access) ?
my startup.cs contains following function.

![image](https://user-images.githubusercontent.com/39464537/42626176-44f88892-85e7-11e8-8b88-e186f2b8c3fe.png)

**Comment by explunit** [comment]
I think your question relates more to how IdentityServer3 works than to how the SAML integration is working, since it's IdentityServer that issues the tokens after the SAML part of the flow. You will probably have better results on StackOverflow for IdentityServer, but the starting point for configuring response type is the `app.UseOpenIdConnectAuthentication` options that you configure.
