### ISSUE TITLE
None of your sample app is working!!

### ISSUE THREAD

**Issue by ved789** [Sustainsys/Saml2#990]
I tried to use this sample app to use Okta as IdP, but none of your sample projects is working, it seems to be complete time-wastage.  I tried to followed instructions given on page: https://github.com/Sustainsys/Saml2/blob/master/docs/IdentityServer3Okta.md
but it's incomplete and utter nonsense. Does anyone have a complete sample app(IdP initated) to use Okta as IdP?

It took only an hour to do the same using Componentspace library.

**Comment by explunit** [comment]
Sorry it didn't work out for you. Can you post the details of what error(s) you are receiving?

**Comment by ved789** [comment]
The problem I am having is, how should I setup the Identity server options as you have not provided any details for this here: 
var options = Helpers.GetIdentityServerOptions();
I didn't get Helpers class anywhere on the web. I can see a similar thread @ https://github.com/Sustainsys/Saml2/issues/383
But this is also incomplete. Incomplete information/documentation is available and that's too in bits and pieces. It's extremely tough and time-consuming to connect all the dots from different forums.
Could you please help as I am stuck here?

**Comment by explunit** [comment]
Was it your goal to use identity server integration, or is that just the example you selected because of the reference to Okta? If you have a simpler scenario, e.g. a single application using a single Okta IDP then you will be better served by the other sample projects (whichever one matches your architecture e.g. OWIN or MVC) and simply plug in the Okta certificate and/or metadata info.

**Comment by ved789** [comment]
As I've already stated my requirements are very very simple.
I need a sample OWIN Service Provider app.
This app will use Okta as IdP.
The app should be Okta Idp-initiated

I've already refereed https://developer.okta.com/blog/2016/03/22/use-kentor-authservices-with-okta link but as I said none of the documents is complete and leads to nowhere. 

Do you still have questions???

Now can you please point me to a sample app that I can refer???

**Comment by ved789** [comment]
I've seen AndersAbel  is very active in answering questions on different forums regarding this library.  But I'd suggest to better complete/update the documentation that people can refer instead of banging head on wall.  Look at the page: https://github.com/Sustainsys/Saml2/blob/b373299f6783c4aec5061890efbcfd1eadfbdc1d/docs/IdentityServer3Okta.md
and try to follow the steps mentioned here, you will feel my pain.

**Comment by explunit** [comment]
It sounds like the SampleOWINApplication would be a better starting point for you. As far as I know. there's nothing special about Okta vs. any other IDP in that sample.

Certainly, better documentation is always helpful, and you are welcome to contribute too since this is open source project. But since none of the maintainers make their primary income by this library it necessarily becomes lesser priority at times.

I'm going to close this issue, but feel free to open more specific issues if you continue to use this library.
