### ISSUE TITLE
Saml endpoint stops working after disabling SSL renegotiation

### ISSUE THREAD

**Issue by rmarilyak** [Sustainsys/Saml2#992]
Hi,

We have several configured Saml2 endpoints based on your Sustainsys.Saml2.HttpModule module.
We are using IIS as our webserver (IIS version 8.5.9600.16384). 
These endpoints are working great until we are trying to disable SSL Renegotiation on server.
It could be done simple by modifying registry key and restarting IIS:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL]
"DisableRenegoOnServer"=dword:00000001

Once its done, all Saml2 edpoints become unavailable. The server simply returns 500 Error.
Also, there are no entries in Windows Event or IIS Logs.
I was unable to find any solution in web or by myself so far.
Can you please help me to solve this issue?

**Comment by rharting** [comment]
I think I'm having the same problem. Our identity provider depreciated the SSL ciphers and now our apps do not work. We now see "Authentication failed because the remote party has closed the transport stream". Did you find a solution?

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
