### ISSUE TITLE
Different Codesource on Nuget

### ISSUE THREAD

**Issue by michaelluethi1986** [Sustainsys/Saml2#993]
I'v intalled the Sustainsys.Saml2.AspNetCore2 package from nuget on my identity server 4 project. After installation i want to cofigure the authentication in startup by copy code from sample project which ends up in buildbreak.
After some analysis the problem could be identified in the Saml2Options and SPOptions. They refers both to Kentor.AuthServices.Configuration wich is not implemented in the actual Github hosted version. Which version should i use?

**Comment by SlaveMast3r** [comment]
Use nugets:
- Microsoft.IdentityModel.Token.Saml (>= 5.2.4.)
- Sustainsys.Saml2 (2.0.0-preview01)
- Sustainsys.Saml2.AspNetCore2 (2.0.0-preview01)

Imports:
- using Microsoft.IdentityModel.Tokens.Saml2;
- using Kentor.AuthServices;
- using Kentor.AuthServices.Metadata;
- using Kentor.AuthServices.WebSso;

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
