### ISSUE TITLE
No way to return back to SP after initiating SP-initiated SLO to IdP

### ISSUE THREAD

**Issue by vidhyasagarreddy** [Sustainsys/Saml2#994]
I don't see a way to return back to SP, after initiating SP-initiated SLO to IdP (Salesforce in my case).

**Comment by explunit** [comment]
The IDP should be redirecting back to the `SingleLogoutService` url published in your metadata or configured separately if you are not using metadata. If this is not happening perhaps the IDP can tell you what error condition they have, e.g. the logout request was not signed with a certificate that they trust.

**Comment by vidhyasagarreddy** [comment]
SingleLogoutService Url is IdP's endpoint for SLO. How do i configure returnURL/some parameter to return user to my app, after SLO is completed ?

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
