### ISSUE TITLE
Implementation of logout 

### ISSUE THREAD

**Issue by dgvinay** [Sustainsys/Saml2#997]
Hi

I am using version 2.0.0 preview.

As per the comment [here](https://github.com/Sustainsys/Saml2/issues/652), I am trying to implement single logout.
In the InitiateLogout method in LogOutCommand.cs, it is looking for LogoutNameIdentifier and SessionIndex. This is supposed to be present in the Claims of the user. In my case this is missing.

Am I supposed to add this explicitly in any of the events during SignIn or is this some kind of a bug?

Thanks,
Vinay

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
