### ISSUE TITLE
Sustainsys.Saml2.Exceptions.NoSamlResponseFoundException after updating NuGet package

### ISSUE THREAD

**Issue by wscalf** [Sustainsys/Saml2#998]
So, I'm using Sustainsys.Saml2 (formerly Kentor.AuthServices) with IdentityServer3 and just updated to the latest package today. After..
* Fixing namespace and class names around OWIN components to the current names
* Changing the redirect url in my test provider from ending with AuthServices/Acs to ending with saml2/acs
* Enabling Microsoft.Owin as a tracing source

..I can almost log in again, but I get the following error upon returning to IdentityServer: Sustainsys.Saml2.Exceptions.NoSamlResponseFoundException: No Saml2 Response found in the http request

The traffic looks like a normal HTTP POST login in Chrome's network tab, and when I set a breakpoint in my global.asax to see what the application actually received, it looks like the url is what I expect and there's a sizable body that looks comparable to what I saw in Chrome, so I don't think it's getting discarded or anything.

I also tried explicitly setting the binding to HttpPost, but no dice. And since I don't know why it isn't recognizing the traffic, I'm kind of just stabbing in the dark here.

This was working prior to updating the package, but it was a biiiig update. Thoughts/advice?

**Comment by AndersAbel** [comment]
This looks like a support question.

Due to the increasing usage of the library the volume of support questions has grown to a point where I simply no longer have time to handle them here on the issue tracker for free.

Moving forward, no new support issues will be accepted on the issue tracker. The number of existing questions is also too large to handle, so I will be closing this.

If you want help for free, please open a question on Stack Overflow and tag it with sustainsys-saml2.

If you want a guaranteed response, please get in touch at support@sustainsys.com to get information about commercial support options.
